### ISSUE TITLE
can't imread picture

### ISSUE THREAD

**Issue by GithubRyze** [DJI-Mobile-SDK/Android-PanoramaDemo#1]
hello friend, i was download your project and running in eclipse.but in Mat mat = imread(filename) this function cannot read image,do you know  why? the jni i can get the /storage/emulated/0/image/pano_20151028_110720.jpg file path,opecv lib 2.4.11. please help me 
thanks!

**Comment by oliverou** [comment]
Hi @GithubRyze, this demo is out-dated, and not maintained currently. We will help to update it in the future. Close it now.
